name: Automatically login in GpuShare webpage

on: workflow_dispatch

env: 
  USERNAME: ${{vars.USERNAME}}
  PASSWORD: ${{vars.PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print username and password
        run: |
          echo $USERNAME
          echo $PASSWORD
