name: test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run download.sh
        run: |
          git clone https://github.com/dop2001/Action.git
          cd Action
          chmod +x scripts/download.sh
          ./scripts/download.sh
          
