name: test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run download.sh
        run: |
          chmod +x scripts/download.sh
          ./download.sh
          
